apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ionos-enterprise-hdd
  resources:
    requests:
      storage: 20Gi # Specify the desired storage size

